name: Rebuild website
on:
  push:
  schedule:
    - cron: '12 1 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - name: Build site
        run: python3 scripts/build.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit downloaded fonts and data
        with:
          file_pattern: index.html sources.json full hinted unhinted
